### bloom filter case
GET http://localhost:8177/api/v1/query?userId=hahaha

### index case
GET http://localhost:8177/api/v1/query?userId=66T1Q5yuc3Xw1sOkcH9Ax3kEuKIAmZ16

### redis case
GET http://localhost:8177/api/v1/query?userId=redis

###
