###
POST http://localhost:9090/setUser
Content-Type: application/json

{
  "id": 111,
  "username": "username111",
  "password": "password111"
}

###
GET http://localhost:9090/getUser?id=111

###
GET http://localhost:9090/findUser?id=1

###
POST http://localhost:9090/saveUser
Content-Type: application/json

{
  "id": 1,
  "username": "username1",
  "password": "password1"
}

###
GET http://localhost:9090/deleteUser?id=1
